version: '3.8'

services:
  # Home Assistant Core
  homeassistant:
    container_name: turtle-homeassistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /opt/turtle-enclosure/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/ttyUSB0:/dev/ttyUSB0  # TEMPerHUM sensor
      - /dev/ttyACM0:/dev/ttyACM0  # Zigbee dongle
      - /dev/video0:/dev/video0    # Camera
    environment:
      - TZ=America/New_York
    depends_on:
      - mosquitto
      - influxdb

  # MQTT Broker
  mosquitto:
    container_name: turtle-mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /opt/turtle-enclosure/config/mosquitto:/mosquitto/config
      - /opt/turtle-enclosure/config/mosquitto/data:/mosquitto/data
      - /opt/turtle-enclosure/config/mosquitto/log:/mosquitto/log
    environment:
      - TZ=America/New_York

  # Zigbee2MQTT
  zigbee2mqtt:
    container_name: turtle-zigbee2mqtt
    image: koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - /opt/turtle-enclosure/config/zigbee2mqtt:/app/data
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=America/New_York
    depends_on:
      - mosquitto

  # InfluxDB for data storage
  influxdb:
    container_name: turtle-influxdb
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - /opt/turtle-enclosure/config/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=turtle123
      - DOCKER_INFLUXDB_INIT_ORG=turtle-enclosure
      - DOCKER_INFLUXDB_INIT_BUCKET=turtle_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=turtle-token-123
      - TZ=America/New_York

  # Grafana for data visualization
  grafana:
    container_name: turtle-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /opt/turtle-enclosure/config/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=turtle123
      - GF_USERS_ALLOW_SIGN_UP=false
      - TZ=America/New_York
    depends_on:
      - influxdb

  # Node-RED for advanced automations
  nodered:
    container_name: turtle-nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - /opt/turtle-enclosure/config/nodered:/data
    environment:
      - TZ=America/New_York
    depends_on:
      - mosquitto

  # Motion for camera streaming
  motion:
    container_name: turtle-motion
    image: motionproject/motion:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "8081:8081"
    volumes:
      - /opt/turtle-enclosure/config/motion:/etc/motion
      - /dev/video0:/dev/video0
    environment:
      - TZ=America/New_York

networks:
  default:
    name: turtle-network 